services:
  milvus:
    image: ${MILVUS_IMAGE:-milvusdb/milvus:v2.6.14}
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_USE_EMBED: "true"
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      ETCD_CONFIG_PATH: /milvus/configs/embedEtcd.yaml
      COMMON_STORAGETYPE: local
      DEPLOY_MODE: STANDALONE
      MILVUSAI_DASHSCOPE_API_KEY: ${MILVUSAI_DASHSCOPE_API_KEY:-}
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    volumes:
      - ./volumes/milvus:/var/lib/milvus
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./user.yaml:/milvus/configs/user.yaml
